name: ade-combinations
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.13.1
  - scikit-learn=1.2.2
  - lightgbm=4.5.0
  - pip:
      - metaforecast==0.2.2