"""FFORMA-style meta-features for cross-dataset memory and meta-learning.

Extracts a fixed-length feature vector from the raw `y_true` signal that
characterises the time series independently of the base predictors.  The
feature set follows Hyndman et al.'s `tsfeatures` package (R) and the
FFORMA paper (Montero-Manso, Athanasopoulos, Hyndman, Talagala, 2020,
*International Journal of Forecasting* 36(1):86-92), with a few additions
for the multi-family base-model setting (FT / CWT / DWT predictors).

The feature vector is the **substrate of the cross-dataset memory** (see
`orchestrator/memory.py`): retrieval of similar past runs is performed
via cosine similarity on these vectors, in the spirit of the experiential
agents of Shinn et al. (2023, NeurIPS — Reflexion) and Zhao et al.
(2024, AAAI — ExpeL).

Design rules:
- Features are computed on the **raw** `y_true` series (validation
  windows concatenated), never on FT/CWT/DWT-transformed signals.
  Family-aware features are computed separately from the per-model
  residuals matrix.
- Every feature is finite or NaN; downstream code (memory) replaces NaN
  by 0 before similarity scoring and z-normalises across the corpus.
- All numeric thresholds and lag choices are exposed in
  `FeatureExtractorConfig` for ablation in the paper.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

from orchestrator.diagnostics import (
    error_similarity_matrix,
    hurst_rs,
    spectral_entropy,
)


EPS = 1e-12


# ──────────────────────────────────────────────────────────────────────────
# Configuration
# ──────────────────────────────────────────────────────────────────────────


@dataclass
class FeatureExtractorConfig:
    """Knobs for the meta-feature extractor.

    Attributes are deliberately exposed so an ablation table in the paper
    can swap them without touching code.
    """

    seasonal_period_hint: Optional[int] = None  # None => infer from horizon
    acf_max_lag: int = 10
    flat_spot_segments: int = 10
    lumpiness_tile_count: int = 10
    family_corr_threshold: float = 0.85  # cluster cutoff on |error correlation|
    use_statsmodels_stl: bool = True


# ──────────────────────────────────────────────────────────────────────────
# Building blocks
# ──────────────────────────────────────────────────────────────────────────


def _safe_float(x: Any) -> float:
    try:
        v = float(x)
        return v if np.isfinite(v) else float("nan")
    except Exception:
        return float("nan")


def _flatten_validation(y_true_2d: np.ndarray) -> np.ndarray:
    """Concatenate window rows into a single 1-D series.

    `y_true_2d` shape is (n_windows, horizon).  We flatten in window order;
    this preserves the rough chronology since validation windows are
    typically generated by an expanding/rolling origin.
    """

    arr = np.asarray(y_true_2d, dtype=float)
    if arr.ndim == 1:
        return arr
    return arr.reshape(-1)


def _autocorrelation(x: np.ndarray, max_lag: int) -> np.ndarray:
    """ACF of a 1-D series for lags 1..max_lag.  Returns NaN-safe vector."""

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < max_lag + 2:
        return np.full(max_lag, np.nan, dtype=float)
    x = x - np.mean(x)
    var = float(np.dot(x, x)) / n
    if var <= 0:
        return np.full(max_lag, np.nan, dtype=float)
    out = np.empty(max_lag, dtype=float)
    for k in range(1, max_lag + 1):
        c = float(np.dot(x[:-k], x[k:])) / n
        out[k - 1] = c / var
    return out


def _trend_seasonal_strength(
    x: np.ndarray, period: int, use_stl: bool = True
) -> Tuple[float, float]:
    """Trend strength F_T and seasonal strength F_S as in Hyndman et al. (2015).

    F_T = max(0, 1 - Var(remainder) / Var(trend + remainder))
    F_S = max(0, 1 - Var(remainder) / Var(seasonal + remainder))

    Falls back to (NaN, NaN) when the series is too short or STL is
    unavailable.
    """

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < max(2 * period + 1, 16) or period < 2:
        return float("nan"), float("nan")

    trend = seasonal = remainder = None
    if use_stl:
        try:
            from statsmodels.tsa.seasonal import STL

            stl = STL(x, period=int(period), robust=True).fit()
            trend = np.asarray(stl.trend, dtype=float)
            seasonal = np.asarray(stl.seasonal, dtype=float)
            remainder = np.asarray(stl.resid, dtype=float)
        except Exception:
            trend = seasonal = remainder = None

    if remainder is None:
        # Cheap fallback: linear detrend + period-mean subtract
        t = np.arange(n, dtype=float)
        a, b = np.polyfit(t, x, 1)
        trend = a * t + b
        detr = x - trend
        seasonal = np.zeros_like(detr)
        for k in range(int(period)):
            idx = np.arange(k, n, int(period))
            if idx.size > 0:
                seasonal[idx] = float(np.mean(detr[idx]))
        remainder = detr - seasonal

    var_r = float(np.var(remainder))
    var_tr = float(np.var(trend + remainder))
    var_sr = float(np.var(seasonal + remainder))
    f_t = max(0.0, 1.0 - var_r / (var_tr + EPS)) if var_tr > 0 else float("nan")
    f_s = max(0.0, 1.0 - var_r / (var_sr + EPS)) if var_sr > 0 else float("nan")
    return float(f_t), float(f_s)


def _linearity_curvature(x: np.ndarray) -> Tuple[float, float]:
    """OLS coefficients on orthogonal polynomials of degree 1 and 2.

    Linearity = standardised slope; curvature = standardised quadratic term.
    Both are unitless (z-scored against the residual std).
    """

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < 4:
        return float("nan"), float("nan")
    t = np.arange(n, dtype=float)
    t = (t - np.mean(t)) / (np.std(t) + EPS)
    t2 = t ** 2
    t2 = (t2 - np.mean(t2)) / (np.std(t2) + EPS)
    X = np.column_stack([np.ones(n), t, t2])
    try:
        beta, *_ = np.linalg.lstsq(X, x, rcond=None)
        resid = x - X @ beta
        sigma = float(np.std(resid)) + EPS
        return float(beta[1] / sigma), float(beta[2] / sigma)
    except Exception:
        return float("nan"), float("nan")


def _stability_lumpiness(x: np.ndarray, n_tiles: int) -> Tuple[float, float]:
    """Stability (variance of tile means) and lumpiness (variance of tile vars).

    Splits the series into `n_tiles` non-overlapping segments.  Lumpy series
    have wildly different sub-variances; unstable series have wildly
    different sub-means.
    """

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < n_tiles * 4:
        return float("nan"), float("nan")
    tile_size = n // n_tiles
    means: List[float] = []
    vars_: List[float] = []
    for i in range(n_tiles):
        seg = x[i * tile_size : (i + 1) * tile_size]
        if seg.size > 1:
            means.append(float(np.mean(seg)))
            vars_.append(float(np.var(seg)))
    if len(means) < 2:
        return float("nan"), float("nan")
    return float(np.var(means)), float(np.var(vars_))


def _flat_spots(x: np.ndarray, n_segments: int) -> int:
    """Maximum run-length of a constant value inside `n_segments` bins."""

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < n_segments:
        return 0
    edges = np.linspace(np.min(x), np.max(x) + EPS, n_segments + 1)
    bins = np.digitize(x, edges) - 1
    max_run = 1
    cur = 1
    for k in range(1, n):
        if bins[k] == bins[k - 1]:
            cur += 1
            if cur > max_run:
                max_run = cur
        else:
            cur = 1
    return int(max_run)


def _crossing_points(x: np.ndarray) -> int:
    """Number of times the series crosses its own median."""

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    if x.size < 2:
        return 0
    med = float(np.median(x))
    above = x > med
    return int(np.sum(above[1:] != above[:-1]))


def _arch_lm(x: np.ndarray, lags: int = 4) -> float:
    """Engle's ARCH-LM statistic on the squared residuals (R^2 * n).

    Higher value => stronger ARCH effect (volatility clustering).  Uses a
    lightweight closed-form OLS rather than statsmodels for portability.
    """

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < lags * 4:
        return float("nan")
    e = (x - np.mean(x)) ** 2
    Y = e[lags:]
    cols = [np.ones(Y.size)]
    for k in range(1, lags + 1):
        cols.append(e[lags - k : n - k])
    X = np.column_stack(cols)
    try:
        beta, *_ = np.linalg.lstsq(X, Y, rcond=None)
        Yh = X @ beta
        ss_res = float(np.sum((Y - Yh) ** 2))
        ss_tot = float(np.sum((Y - np.mean(Y)) ** 2)) + EPS
        r2 = max(0.0, 1.0 - ss_res / ss_tot)
        return float(r2 * Y.size)
    except Exception:
        return float("nan")


def _kpss_stat(x: np.ndarray) -> float:
    """KPSS level-stationarity statistic via statsmodels (NaN if unavailable)."""

    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    if x.size < 16:
        return float("nan")
    try:
        from statsmodels.tsa.stattools import kpss

        # nlags='auto' produces a warning but is robust; suppress with try/except
        stat, _, _, _ = kpss(x, regression="c", nlags="auto")
        return float(stat)
    except Exception:
        return float("nan")


# ──────────────────────────────────────────────────────────────────────────
# Family-aware features (specific to the FT / CWT / DWT base-model setting)
# ──────────────────────────────────────────────────────────────────────────


def _infer_family(model_name: str) -> str:
    """Heuristic family tag from model name.  Returns one of FT/CWT/DWT/HYBRID/OTHER.

    The repository convention names base predictors with substrings such as
    `_ft`, `_cwt`, `_dwt`, etc.  Hybrid models contain more than one tag.
    """

    name = model_name.lower()
    tags = []
    if "ft" in name or "fft" in name or "fourier" in name:
        tags.append("FT")
    if "cwt" in name or "continuous_wavelet" in name:
        tags.append("CWT")
    if "dwt" in name or "discrete_wavelet" in name or "wavelet" in name:
        tags.append("DWT")
    if not tags:
        return "OTHER"
    if len(tags) == 1:
        return tags[0]
    return "HYBRID"


def _family_aware_features(
    y_true: np.ndarray,
    y_preds: np.ndarray,
    model_names: List[str],
    corr_threshold: float,
) -> Dict[str, float]:
    """Family stats: best family by RMSE, redundancy clusters from error matrix.

    `y_true` shape (n_windows, horizon); `y_preds` shape (n_windows, n_models, horizon).
    """

    y = np.asarray(y_true, dtype=float)
    P = np.asarray(y_preds, dtype=float)
    if P.ndim != 3 or P.shape[0] == 0:
        return {
            "best_family_one_hot_FT": 0.0,
            "best_family_one_hot_CWT": 0.0,
            "best_family_one_hot_DWT": 0.0,
            "best_family_one_hot_HYBRID": 0.0,
            "best_family_one_hot_OTHER": 0.0,
            "n_error_clusters_norm": float("nan"),
            "intra_family_redundancy": float("nan"),
        }

    n_w, n_m, h = P.shape
    families = [_infer_family(m) for m in model_names]

    # Per-model average RMSE
    err = P - y[:, None, :]
    rmse_per_model = np.sqrt(np.nanmean(err ** 2, axis=(0, 2)))

    # Best family = family of model with min RMSE
    best_idx = int(np.nanargmin(rmse_per_model))
    best_family = families[best_idx]

    # Cluster the error-similarity matrix above corr_threshold to count
    # effective number of independent error-modes (proxy for diversity).
    errors_flat = err.reshape(n_m, -1)
    sim = error_similarity_matrix(errors_flat)
    # Greedy clustering via |corr| > threshold
    n_clusters = 1
    if errors_flat.shape[0] >= 2:
        # Build adjacency using pairwise correlations
        adj = np.zeros((n_m, n_m), dtype=int)
        for i in range(n_m):
            for j in range(i + 1, n_m):
                xi = errors_flat[i]
                xj = errors_flat[j]
                mask = (~np.isnan(xi)) & (~np.isnan(xj))
                if int(np.sum(mask)) < 3:
                    continue
                a = xi[mask] - np.mean(xi[mask])
                b = xj[mask] - np.mean(xj[mask])
                denom = float(np.std(a) * np.std(b))
                if denom < EPS:
                    continue
                c = abs(float(np.dot(a, b) / (a.size * denom)))
                if c >= corr_threshold:
                    adj[i, j] = 1
                    adj[j, i] = 1
        # Connected components
        seen = [False] * n_m
        n_clusters = 0
        for s in range(n_m):
            if seen[s]:
                continue
            n_clusters += 1
            stack = [s]
            while stack:
                v = stack.pop()
                if seen[v]:
                    continue
                seen[v] = True
                for u in range(n_m):
                    if adj[v, u] and not seen[u]:
                        stack.append(u)

    # Within-family redundancy: mean |corr| among same-family models only.
    intra_corr: List[float] = []
    fam_set = set(families)
    for f in fam_set:
        idxs = [i for i, fi in enumerate(families) if fi == f]
        if len(idxs) < 2:
            continue
        for i in idxs:
            for j in idxs:
                if i >= j:
                    continue
                xi = errors_flat[i]
                xj = errors_flat[j]
                mask = (~np.isnan(xi)) & (~np.isnan(xj))
                if int(np.sum(mask)) < 3:
                    continue
                a = xi[mask] - np.mean(xi[mask])
                b = xj[mask] - np.mean(xj[mask])
                denom = float(np.std(a) * np.std(b))
                if denom < EPS:
                    continue
                intra_corr.append(abs(float(np.dot(a, b) / (a.size * denom))))
    intra = float(np.mean(intra_corr)) if intra_corr else float("nan")

    one_hot = {f"best_family_one_hot_{f}": 0.0 for f in ("FT", "CWT", "DWT", "HYBRID", "OTHER")}
    one_hot[f"best_family_one_hot_{best_family}"] = 1.0
    one_hot["n_error_clusters_norm"] = float(n_clusters) / float(max(1, n_m))
    one_hot["intra_family_redundancy"] = intra
    return one_hot


# ──────────────────────────────────────────────────────────────────────────
# Top-level extractor
# ──────────────────────────────────────────────────────────────────────────


def extract_features(
    y_true: np.ndarray,
    y_preds: Optional[np.ndarray] = None,
    model_names: Optional[List[str]] = None,
    cfg: Optional[FeatureExtractorConfig] = None,
) -> Dict[str, float]:
    """Compute the FFORMA-style meta-feature dictionary for one dataset.

    Args:
        y_true: shape (n_windows, horizon) — validation truth.  Will be
            flattened in window order.
        y_preds: optional shape (n_windows, n_models, horizon).  If
            provided together with `model_names`, family-aware features are
            added.
        model_names: optional list of base-model names (for family detection).
        cfg: optional `FeatureExtractorConfig`.

    Returns:
        Dict[str, float] with ~25 features.  Missing/undefined values are
        NaN; downstream cosine retrieval handles NaN -> 0 imputation.
    """

    cfg = cfg or FeatureExtractorConfig()
    y2d = np.asarray(y_true, dtype=float)
    if y2d.ndim == 1:
        y2d = y2d.reshape(1, -1)
    horizon = int(y2d.shape[1])
    series = _flatten_validation(y2d)

    period = int(cfg.seasonal_period_hint) if cfg.seasonal_period_hint else max(2, min(24, horizon))
    f_t, f_s = _trend_seasonal_strength(series, period, use_stl=cfg.use_statsmodels_stl)
    lin, curv = _linearity_curvature(series)
    stab, lump = _stability_lumpiness(series, cfg.lumpiness_tile_count)

    acf = _autocorrelation(series, cfg.acf_max_lag)
    diff_series = np.diff(series)
    diff_acf = _autocorrelation(diff_series, cfg.acf_max_lag)

    feats: Dict[str, float] = {
        # Length / scale
        "length": float(series.size),
        "horizon": float(horizon),
        "n_windows": float(y2d.shape[0]),
        "mean": _safe_float(np.nanmean(series)),
        "std": _safe_float(np.nanstd(series)),
        "cv": _safe_float(np.nanstd(series) / (abs(np.nanmean(series)) + EPS)),
        # Distribution shape
        "skewness": _safe_float(_moment_skew(series)),
        "kurtosis": _safe_float(_moment_kurtosis(series)),
        # Structure (Hyndman et al. 2015)
        "trend_strength": _safe_float(f_t),
        "seasonal_strength": _safe_float(f_s),
        "linearity": _safe_float(lin),
        "curvature": _safe_float(curv),
        # Information / memory
        "spectral_entropy": _safe_float(spectral_entropy(series)),
        "hurst": _safe_float(hurst_rs(series)),
        # ACF features
        "acf1": _safe_float(acf[0]) if acf.size else float("nan"),
        "acf10_sumsq": _safe_float(np.nansum(acf ** 2)) if acf.size else float("nan"),
        "diff1_acf1": _safe_float(diff_acf[0]) if diff_acf.size else float("nan"),
        "diff1_acf10_sumsq": _safe_float(np.nansum(diff_acf ** 2)) if diff_acf.size else float("nan"),
        # Tile stats
        "stability": _safe_float(stab),
        "lumpiness": _safe_float(lump),
        "flat_spots": _safe_float(_flat_spots(series, cfg.flat_spot_segments)),
        "crossing_points_norm": _safe_float(_crossing_points(series) / max(1.0, series.size)),
        # Volatility / stationarity
        "arch_lm": _safe_float(_arch_lm(series)),
        "kpss_stat": _safe_float(_kpss_stat(series)),
    }

    if y_preds is not None and model_names is not None and len(model_names) > 0:
        feats.update(
            _family_aware_features(
                y2d, np.asarray(y_preds, dtype=float), list(model_names), cfg.family_corr_threshold
            )
        )

    return feats


def _moment_skew(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < 3:
        return float("nan")
    m = float(np.mean(x))
    s = float(np.std(x)) + EPS
    return float(np.mean(((x - m) / s) ** 3))


def _moment_kurtosis(x: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    n = int(x.size)
    if n < 4:
        return float("nan")
    m = float(np.mean(x))
    s = float(np.std(x)) + EPS
    return float(np.mean(((x - m) / s) ** 4) - 3.0)  # excess kurtosis


# ──────────────────────────────────────────────────────────────────────────
# Identity (used by memory.py to deduplicate runs)
# ──────────────────────────────────────────────────────────────────────────


def compute_dataset_id(
    y_true: np.ndarray,
    model_names: List[str],
    explicit_id: Optional[str] = None,
) -> str:
    """Deterministic dataset identifier.

    If `explicit_id` is supplied (e.g. `M4_monthly_1234`) it is returned
    verbatim; otherwise a stable SHA-256 hex prefix derived from the data
    shape and the first window's `y_true` is returned.
    """

    if explicit_id and str(explicit_id).strip():
        return str(explicit_id).strip()
    y = np.asarray(y_true, dtype=float)
    payload = {
        "shape": [int(s) for s in y.shape],
        "models": list(map(str, model_names)),
        "first_window": [round(float(v), 6) for v in y[0].tolist()] if y.size else [],
    }
    blob = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return "ds_" + hashlib.sha256(blob).hexdigest()[:16]


def feature_vector(features: Dict[str, float], schema: Optional[List[str]] = None) -> np.ndarray:
    """Materialise a `Dict[str, float]` into a fixed-order numpy vector.

    If `schema` is provided, missing keys are filled with NaN.  Otherwise
    keys are sorted lexicographically.
    """

    keys = list(schema) if schema is not None else sorted(features.keys())
    out = np.array([features.get(k, float("nan")) for k in keys], dtype=float)
    return out
